sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t luismiguellara2106/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true luismiguellara2106/docker-react npm run test